/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteAlexArgs } from "./DeleteAlexArgs";
import { AlexFindManyArgs } from "./AlexFindManyArgs";
import { AlexFindUniqueArgs } from "./AlexFindUniqueArgs";
import { Alex } from "./Alex";
import { AlexService } from "../alex.service";

@graphql.Resolver(() => Alex)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AlexResolverBase {
  constructor(
    protected readonly service: AlexService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Alex",
    action: "read",
    possession: "any",
  })
  async _alexesMeta(
    @graphql.Args() args: AlexFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Alex])
  @nestAccessControl.UseRoles({
    resource: "Alex",
    action: "read",
    possession: "any",
  })
  async alexes(@graphql.Args() args: AlexFindManyArgs): Promise<Alex[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Alex, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Alex",
    action: "read",
    possession: "own",
  })
  async alex(@graphql.Args() args: AlexFindUniqueArgs): Promise<Alex | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Alex)
  @nestAccessControl.UseRoles({
    resource: "Alex",
    action: "delete",
    possession: "any",
  })
  async deleteAlex(@graphql.Args() args: DeleteAlexArgs): Promise<Alex | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
